name: bakecode_jobs
description: A starting point for Dart libraries or applications.
version: 0.0.0
homepage: https://github.com/crysalisdevs/bakecode-jobs.git

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  equatable:
  meta:

dev_dependencies:
  
