name: bakecode_jobs
description: BakeCode Jobs and Node API
version: 0.1.0-alpha
homepage: https://github.com/crysalisdevs/bakecode-jobs.git

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  meta:

dev_dependencies:
  
