name: bakecode
description: BakeCode Framework, perform actions in bakecode ecosystem.
version: 0.1.0-alpha
homepage: https://github.com/crysalisdevs/bakecode-jobs.git

publish_to: "none"

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  meta:
